name: localization-algorithm
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - ipython
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - imageio
